name: lint

on:
  push:
    branches:
    - master

jobs:
  go:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        go: [1.15]
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Setup go env ${{ matrix.go }}
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go }}

    - name: Install dependencies
      run: |
        go version
        go get -v golang.org/x/lint/golint

    - name: Run vet and lint
      working-directory: ./study/algorithm/
      run: |
        go vet ./...
        golint -set_exit_status ./...
